### ISSUE TITLE
Beginner help - How to use

### ISSUE THREAD

**Issue by Jakob37** [linem/mjewel-plotting-tool#5]
How can I use the package? I have installed it, and can see it among the installed packages:

```
(mjewel) jakob@laptop:~/src/mjewel-plotting-tool$ pip freeze
contourpy==1.3.0
cycler==0.12.1
fonttools==4.53.1
kiwisolver==1.4.5
matplotlib==3.9.2
mjewel-plotting-tool==0.1.0
numpy==2.1.0
packaging==24.1
pandas==2.2.2
pillow==10.4.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
pytz==2024.1
six==1.16.0
tzdata==2024.1
```

But I cannot import it

```
>>> import mjewel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mjewel'
>>> import mjewel-plotting-tool
  File "<stdin>", line 1
    import mjewel-plotting-tool
                 ^
SyntaxError: invalid syntax
```

**Comment by linem** [comment]
I have fixed the installation.
It is possible to import the package as a module, however (currently) the intended use of the package is to be used a command line tool. I have updated the readme file with a better description of how to install and use it.
Let me know if you still have problems.

**Comment by Jakob37** [comment]
Great!
